# hand-on

#server:
#  tomcat:
#    min-spare: 1
#    accept-count: 1
#    max-connections: 3
#    threads:
#      max: 2

# sihyung92 velog

server:
  tomcat:
    threads:
      max: 2
      min-spare: 2
    accept-count: 1
  port: 5000

# --server.tomcat.threads.max=2
# --server.tomcat.threads.min-spare=2
# --server.tomcat.accept-count=1
# --server.port=8088

# --server.tomcat.threads.min-spare=1 --server.tomcat.threads.max=1 --server.tomcat.accept-count=1 --server.port=8088
